TEMP: comment date parsing
This parses strings like "0001" (which in context of pza is a police
zone code) to datetime (year 0), which is obviously incorrect. This
leads then to other problems.

Error it raises:
```
 File "/app/.local/lib/python3.12/site-packages/elody/util.py", line 54, in default
return self.__convert_datetime(obj)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.local/lib/python3.12/site-packages/elody/util.py", line 48, in __convert_datetime
obj = obj.astimezone(timezone.utc)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
```